name: pydataanalysis
channels:
  - defaults
  - conda-forge
dependencies:
  - black
  - flake8
  - jupyter
  - jupytext
  - toml
  - matplotlib
  - numpy
  - scipy
  - pandas
  - xarray
  - h5netcdf
  - matplotlib
  - statsmodels
  - scikit-learn
  - bokeh
  - selenium
  - python-chromedriver-binary
  - holoviews
  - hvplot
  - panel
  - pip
  - pytest
  - pandoc
  - pandoc-crossref
  - panflute
  - tabulate
  - pip:
    - -e .
    - pandoc-img-glob
